language: python
sudo: required
services:
  - docker

script:
  - git clone git://github.com/openmicroscopy/omero-test-infra .omero
  - .omero/docker lib

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
